"""Read-only release identity from loaded package bytes, without optional imports.

The bundled manifest is a release consistency record, not a cryptographic signature.
It deliberately excludes itself and interpreter-generated bytecode.
"""
from __future__ import annotations

import ast
import hashlib
from importlib import metadata, util
import json
from pathlib import Path, PurePosixPath
import re
import sys
import tomllib


PACKAGE_LAYOUT = (
    ('library-tools', 'librarytools', 'librarytools'),
    ('sample-tools', 'sampletools', 'sampletools'),
    ('ableton-tools', 'abletontools', 'abletontools'),
    ('live-tools', 'eideticlive', 'eidetic-live-tools'),
)
MANIFEST_PATH = Path('library-tools/src/librarytools/resources/release.json')
_VERSION = re.compile(r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\Z')


def _version_tuple(version: str) -> tuple[int, int, int]:
    """Release tooling accepts stable SemVer versions, independent per package."""
    if not isinstance(version, str) or not _VERSION.fullmatch(version):
        raise ValueError(f'invalid release version {version!r}; expected MAJOR.MINOR.PATCH')
    return tuple(map(int, version.split('.')))


def _included_file(relative: str, module: str) -> bool:
    path = PurePosixPath(relative)
    return ('__pycache__' not in path.parts and path.suffix not in {'.pyc', '.pyo'}
            and not (module == 'librarytools' and relative == 'resources/release.json'))


def _source_hashes(source: Path) -> dict[str, str]:
    if not (source / '__init__.py').is_file():
        raise ValueError(f'package source is missing: {source}')
    return {file.relative_to(source).as_posix(): hashlib.sha256(file.read_bytes()).hexdigest()
            for file in sorted(source.rglob('*'))
            if file.is_file() and _included_file(file.relative_to(source).as_posix(), source.name)}


def _project_version(path: Path, distribution: str) -> str:
    project = tomllib.loads(path.read_text(encoding='utf-8')).get('project', {})
    if not isinstance(project, dict) or project.get('name') != distribution:
        raise ValueError(f'{path} does not declare {distribution}')
    version = project.get('version')
    _version_tuple(version)
    return version


def _checkout_packages(checkout: Path) -> dict:
    packages = {}
    for folder, module, distribution in PACKAGE_LAYOUT:
        source = checkout / folder / 'src' / module
        version = _project_version(checkout / folder / 'pyproject.toml', distribution)
        declared = _declared_version(source)
        if declared is not None and declared != version:
            raise ValueError(f'{distribution}: __version__ {declared} differs from project version {version}')
        packages[distribution] = {
            'path': folder, 'module': module,
            'version': version, 'files': _source_hashes(source),
        }
    return packages


def _read_manifest(path: Path) -> dict:
    manifest = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(manifest, dict) or type(manifest.get('manifest_version')) is not int:
        raise ValueError('release manifest has no supported manifest_version')
    if manifest['manifest_version'] != 1:
        raise ValueError(f'unsupported release manifest version {manifest["manifest_version"]}')
    packages = manifest.get('packages')
    if not isinstance(packages, dict) or set(packages) != {row[2] for row in PACKAGE_LAYOUT}:
        raise ValueError('release manifest must describe all four packages')
    for folder, module, distribution in PACKAGE_LAYOUT:
        package = packages[distribution]
        if not isinstance(package, dict) or package.get('module') != module or package.get('path') != folder:
            raise ValueError(f'invalid package identity in release manifest: {distribution}')
        _version_tuple(package.get('version'))
        files = package.get('files')
        if not isinstance(files, dict) or '__init__.py' not in files:
            raise ValueError(f'missing package hashes in release manifest: {distribution}')
        for name, digest in files.items():
            relative = PurePosixPath(name)
            if (not name or '\\' in name or relative.is_absolute() or '..' in relative.parts
                    or relative.as_posix() != name or not _included_file(name, module)
                    or not isinstance(digest, str) or not re.fullmatch(r'[0-9a-f]{64}', digest)):
                raise ValueError(f'invalid release hash entry: {distribution}/{name}')
    return manifest


def _differences(expected: dict[str, str], actual: dict[str, str]) -> dict[str, list[str]]:
    return {
        'changed_files': sorted(name for name in expected.keys() & actual.keys()
                                if expected[name] != actual[name]),
        'missing_files': sorted(expected.keys() - actual.keys()),
        'unexpected_files': sorted(actual.keys() - expected.keys()),
    }


def _package_source(module: str) -> Path | None:
    """Use already-loaded module locations before import discovery; never import."""
    loaded = sys.modules.get(module)
    if loaded is not None:
        origin = getattr(loaded, '__file__', None)
    else:
        spec = util.find_spec(module)
        origin = spec.origin if spec is not None else None
    return Path(origin).resolve().parent if origin and origin not in {'built-in', 'frozen'} else None


def _declared_version(source: Path) -> str | None:
    """Read an initializer's optional version constant without importing it."""
    tree = ast.parse((source / '__init__.py').read_text(encoding='utf-8'))
    for statement in tree.body:
        if isinstance(statement, ast.Assign) and any(
                isinstance(target, ast.Name) and target.id == '__version__'
                for target in statement.targets):
            if isinstance(statement.value, ast.Constant) and isinstance(statement.value.value, str):
                return statement.value.value
    return None


def _loaded_version(source: Path, module: str, distribution: str, installed) -> str | None:
    project = source.parent.parent / 'pyproject.toml'
    if source.parent.name == 'src' and project.is_file():
        return _project_version(project, distribution)
    if installed is not None and Path(installed.locate_file(module)).resolve() == source:
        return installed.version
    return _declared_version(source)


def runtime_report(checkout: Path | None = None) -> dict:
    """Compare active packages with their release and an optional local checkout.

    Missing optional packages are informational. An unreadable contract or selected
    checkout blocks verification; byte/version drift requests an explicit install.
    Ordinary inspection performs no network, database or audio operations.
    """
    report = {'contract_version': 1, 'status': 'ready', 'packages': {}, 'issues': [], 'actions': []}
    issues = report['issues']
    manifest = None
    blocked = False
    needs_install = set()
    try:
        source = _package_source('librarytools')
        if source is None:
            raise ValueError('required librarytools package is missing')
        manifest = _read_manifest(source / 'resources/release.json')
    except (OSError, ValueError, TypeError) as error:
        issues.append(f'Cannot verify release manifest: {error}')
        blocked = True
        needs_install.add('librarytools')

    selected = None
    checkout_path = Path(checkout).expanduser().resolve() if checkout is not None else None
    if checkout_path is not None:
        try:
            selected = _checkout_packages(checkout_path)
        except (OSError, ValueError, TypeError, SyntaxError) as error:
            issues.append(f'Cannot verify selected checkout: {error}')
            blocked = True

    for folder, module, distribution in PACKAGE_LAYOUT:
        expected = manifest['packages'][distribution] if manifest else None
        detail = {
            'module': module, 'required': distribution == 'librarytools', 'status': 'unverified',
            'expected_version': expected['version'] if expected else None,
            'loaded_version': None, 'installed_version': None, 'source_path': None,
            'changed_files': [], 'missing_files': [], 'unexpected_files': [],
        }
        report['packages'][distribution] = detail
        if checkout_path is not None:
            detail.update(checkout_version=selected[distribution]['version'] if selected else None,
                          checkout_matches=None)
        try:
            try:
                installed = metadata.distribution(distribution)
            except metadata.PackageNotFoundError:
                installed = None
            detail['installed_version'] = installed.version if installed is not None else None
            source = _package_source(module)
            if source is None:
                if detail['required']:
                    issues.append(f'Required package is missing: {distribution}')
                    needs_install.add(distribution)
                    blocked = True
                elif installed is not None:
                    detail['status'] = 'drift'
                    detail['missing_files'] = sorted(expected['files']) if expected else []
                    issues.append(f'{distribution}: installed metadata exists but its package source is missing')
                    needs_install.add(distribution)
                    if selected is not None:
                        detail['checkout_matches'] = False
                else:
                    detail['status'] = 'missing_optional'
                continue
            detail['source_path'] = str(source)
            detail['loaded_version'] = _loaded_version(source, module, distribution, installed)
            actual = _source_hashes(source)
            if expected:
                detail.update(_differences(expected['files'], actual))
                drift = any(detail[field] for field in ('changed_files', 'missing_files', 'unexpected_files'))
                if drift or detail['loaded_version'] != expected['version']:
                    detail['status'] = 'drift'
                    issues.append(f'{distribution}: active bytes or version differ from the bundled release')
                    needs_install.add(distribution)
                else:
                    detail['status'] = 'verified'
            if selected is not None:
                candidate = selected[distribution]
                detail['checkout_matches'] = (actual == candidate['files']
                                               and detail['loaded_version'] == candidate['version'])
                if not detail['checkout_matches']:
                    detail['status'] = 'drift'
                    issues.append(f'{distribution}: active bytes or version differ from the selected checkout')
                    needs_install.add(distribution)
        except (OSError, ValueError, TypeError, SyntaxError) as error:
            issues.append(f'Cannot verify {distribution}: {error}')
            blocked = True
            needs_install.add(distribution)

    report['status'] = 'blocked' if blocked else ('action_required' if needs_install else 'ready')
    if needs_install and (checkout_path is None or selected is not None):
        targets = []
        for folder, _, distribution in PACKAGE_LAYOUT:
            if distribution in needs_install:
                version = report['packages'][distribution]['expected_version']
                targets.append(str(checkout_path / folder) if selected is not None
                               else f'{distribution}=={version}' if version else distribution)
        report['actions'].append({
            'id': 'install_release',
            'reason': ('Install the selected tested release while preserving existing dependencies. '
                       f'After installation, run {sys.executable} -m pip check, then rerun '
                       'sample-library version and sample-library status.'),
            'argv': [sys.executable, '-m', 'pip', 'install', '--upgrade', '--force-reinstall', '--no-deps', *targets],
        })
    return report
